import mongoose from "mongoose";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: resolve(__dirname, '.env') });

import Vehicle from "./models/vehicleModel.js";

const vehicles = [
  {
    registeration_number: "KA-01-AB-1234",
    name: "Swift Dzire",
    company: "Maruti Suzuki",
    model: "Dzire VXI",
    year_made: 2023,
    fuel_type: "petrol",
    seats: 5,
    transmition: "manual",
    car_type: "Sedan",
    price: 1500,
    description: "Comfortable sedan perfect for city rides and highway trips.",
    image: ["https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=600&h=400&fit=crop"],
    location: "Bangalore",
    district: "Bangalore Urban",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "KA-02-CD-5678",
    name: "Hyundai Creta",
    company: "Hyundai",
    model: "Creta SX",
    year_made: 2024,
    fuel_type: "diesel",
    seats: 5,
    transmition: "automatic",
    car_type: "SUV",
    price: 3500,
    description: "Premium SUV with sunroof, ventilated seats, and ADAS features.",
    image: ["https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&h=400&fit=crop"],
    location: "Mumbai",
    district: "Mumbai",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "TN-03-EF-9012",
    name: "Toyota Innova Crysta",
    company: "Toyota",
    model: "Crysta GX",
    year_made: 2023,
    fuel_type: "diesel",
    seats: 7,
    transmition: "manual",
    car_type: "MUV",
    price: 4000,
    description: "Spacious 7-seater MPV ideal for family road trips.",
    image: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&h=400&fit=crop"],
    location: "Chennai",
    district: "Chennai",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "MH-04-GH-3456",
    name: "Tata Nexon EV",
    company: "Tata",
    model: "Nexon EV Max",
    year_made: 2024,
    fuel_type: "electirc",
    seats: 5,
    transmition: "automatic",
    car_type: "SUV",
    price: 2800,
    description: "Electric SUV with 437 km range and fast charging support.",
    image: ["https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=600&h=400&fit=crop"],
    location: "Pune",
    district: "Pune",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "DL-05-IJ-7890",
    name: "Mahindra Thar",
    company: "Mahindra",
    model: "Thar LX",
    year_made: 2023,
    fuel_type: "diesel",
    seats: 4,
    transmition: "manual",
    car_type: "SUV",
    price: 3200,
    description: "Iconic off-roader with 4x4, convertible top, and rugged styling.",
    image: ["https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&h=400&fit=crop"],
    location: "Delhi",
    district: "New Delhi",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "KA-06-KL-1122",
    name: "Honda City",
    company: "Honda",
    model: "City ZX",
    year_made: 2023,
    fuel_type: "petrol",
    seats: 5,
    transmition: "automatic",
    car_type: "Sedan",
    price: 2200,
    description: "Elegant sedan with a refined CVT and premium interior.",
    image: ["https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&h=400&fit=crop"],
    location: "Bangalore",
    district: "Bangalore Urban",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "KL-07-MN-3344",
    name: "Kia Seltos",
    company: "Kia",
    model: "Seltos HTX",
    year_made: 2024,
    fuel_type: "petrol",
    seats: 5,
    transmition: "automatic",
    car_type: "SUV",
    price: 2900,
    description: "Feature-packed SUV with a 10.25-inch display and ADAS.",
    image: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&h=400&fit=crop"],
    location: "Kochi",
    district: "Ernakulam",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "TN-08-OP-5566",
    name: "Maruti Baleno",
    company: "Maruti Suzuki",
    model: "Baleno Alpha",
    year_made: 2023,
    fuel_type: "petrol",
    seats: 5,
    transmition: "manual",
    car_type: "Hatchback",
    price: 1200,
    description: "Sporty hatchback with heads-up display and 360-degree camera.",
    image: ["https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&h=400&fit=crop"],
    location: "Coimbatore",
    district: "Coimbatore",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "MH-09-QR-7788",
    name: "Tata Harrier",
    company: "Tata",
    model: "Harrier XZ+",
    year_made: 2024,
    fuel_type: "diesel",
    seats: 5,
    transmition: "automatic",
    car_type: "SUV",
    price: 3600,
    description: "Bold design SUV based on Land Rover's D8 platform.",
    image: ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&h=400&fit=crop"],
    location: "Mumbai",
    district: "Mumbai",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "DL-10-ST-9900",
    name: "MG Hector",
    company: "MG Motor",
    model: "Hector Sharp",
    year_made: 2023,
    fuel_type: "hybrid",
    seats: 5,
    transmition: "automatic",
    car_type: "SUV",
    price: 3100,
    description: "Connected SUV with 14-inch infotainment and hybrid powertrain.",
    image: ["https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&h=400&fit=crop"],
    location: "Delhi",
    district: "New Delhi",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "KA-11-UV-1133",
    name: "Volkswagen Virtus",
    company: "Volkswagen",
    model: "Virtus GT",
    year_made: 2024,
    fuel_type: "petrol",
    seats: 5,
    transmition: "automatic",
    car_type: "Sedan",
    price: 2500,
    description: "Sporty German sedan with TSI turbo engine and 6-speed AT.",
    image: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&h=400&fit=crop"],
    location: "Bangalore",
    district: "Bangalore Urban",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "RJ-12-WX-2244",
    name: "Toyota Fortuner",
    company: "Toyota",
    model: "Fortuner 4x4",
    year_made: 2023,
    fuel_type: "diesel",
    seats: 7,
    transmition: "automatic",
    car_type: "SUV",
    price: 5500,
    description: "Flagship full-size SUV built for long-distance luxury travel.",
    image: ["https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&h=400&fit=crop"],
    location: "Jaipur",
    district: "Jaipur",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "GJ-13-YZ-3355",
    name: "Hyundai Venue",
    company: "Hyundai",
    model: "Venue SX+ DCT",
    year_made: 2024,
    fuel_type: "petrol",
    seats: 5,
    transmition: "automatic",
    car_type: "SUV",
    price: 1800,
    description: "Compact SUV with connected car features and dual-clutch auto.",
    image: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&h=400&fit=crop"],
    location: "Ahmedabad",
    district: "Ahmedabad",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "WB-14-AB-4466",
    name: "Tata Punch",
    company: "Tata",
    model: "Punch Adventure",
    year_made: 2023,
    fuel_type: "petrol",
    seats: 5,
    transmition: "manual",
    car_type: "Hatchback",
    price: 1000,
    description: "Micro SUV with 5-star safety and high ground clearance.",
    image: ["https://images.unsplash.com/photo-1542362567-b07e54358753?w=600&h=400&fit=crop"],
    location: "Kolkata",
    district: "Kolkata",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
  {
    registeration_number: "KA-15-CD-5577",
    name: "BMW 3 Series",
    company: "BMW",
    model: "320d M Sport",
    year_made: 2024,
    fuel_type: "diesel",
    seats: 5,
    transmition: "automatic",
    car_type: "Sedan",
    price: 8000,
    description: "Luxury sports sedan with M Sport suspension and iDrive 8.",
    image: ["https://images.unsplash.com/photo-1556189250-72ba954cfc2b?w=600&h=400&fit=crop"],
    location: "Bangalore",
    district: "Bangalore Urban",
    isDeleted: false,
    isBooked: false,
    isAdminApproved: true,
    isAdminAdded: true,
    addedBy: "admin",
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.mongo_uri);
    console.log("✅ MongoDB connected for seeding");

    await Vehicle.deleteMany({});
    console.log("🗑️  Cleared old vehicles");

    const result = await Vehicle.insertMany(vehicles);
    console.log(`🚗 Seeded ${result.length} vehicles successfully!`);

    await mongoose.disconnect();
    console.log("✅ Done — disconnected");
    process.exit(0);
  } catch (err) {
    console.error("❌ Seed failed:", err.message);
    process.exit(1);
  }
}

seed();
